/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesIndexRouteImport } from './routes/stories.index'
import { Route as StoriesStoryIdRouteImport } from './routes/stories.$storyId'
import { Route as PlayQuizRouteImport } from './routes/play.quiz'
import { Route as PlayMatchingRouteImport } from './routes/play.matching'
import { Route as PlayFlashcardsRouteImport } from './routes/play.flashcards'
import { Route as CategoryCategoryIdRouteImport } from './routes/category.$categoryId'
import { Route as AgesAgeIdRouteImport } from './routes/ages.$ageId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStoryIdRoute = StoriesStoryIdRouteImport.update({
  id: '/stories/$storyId',
  path: '/stories/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayQuizRoute = PlayQuizRouteImport.update({
  id: '/play/quiz',
  path: '/play/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayMatchingRoute = PlayMatchingRouteImport.update({
  id: '/play/matching',
  path: '/play/matching',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayFlashcardsRoute = PlayFlashcardsRouteImport.update({
  id: '/play/flashcards',
  path: '/play/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryIdRoute = CategoryCategoryIdRouteImport.update({
  id: '/category/$categoryId',
  path: '/category/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgesAgeIdRoute = AgesAgeIdRouteImport.update({
  id: '/ages/$ageId',
  path: '/ages/$ageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ages/$ageId': typeof AgesAgeIdRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/play/flashcards': typeof PlayFlashcardsRoute
  '/play/matching': typeof PlayMatchingRoute
  '/play/quiz': typeof PlayQuizRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ages/$ageId': typeof AgesAgeIdRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/play/flashcards': typeof PlayFlashcardsRoute
  '/play/matching': typeof PlayMatchingRoute
  '/play/quiz': typeof PlayQuizRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/stories': typeof StoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ages/$ageId': typeof AgesAgeIdRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/play/flashcards': typeof PlayFlashcardsRoute
  '/play/matching': typeof PlayMatchingRoute
  '/play/quiz': typeof PlayQuizRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ages/$ageId'
    | '/category/$categoryId'
    | '/play/flashcards'
    | '/play/matching'
    | '/play/quiz'
    | '/stories/$storyId'
    | '/stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ages/$ageId'
    | '/category/$categoryId'
    | '/play/flashcards'
    | '/play/matching'
    | '/play/quiz'
    | '/stories/$storyId'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/ages/$ageId'
    | '/category/$categoryId'
    | '/play/flashcards'
    | '/play/matching'
    | '/play/quiz'
    | '/stories/$storyId'
    | '/stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgesAgeIdRoute: typeof AgesAgeIdRoute
  CategoryCategoryIdRoute: typeof CategoryCategoryIdRoute
  PlayFlashcardsRoute: typeof PlayFlashcardsRoute
  PlayMatchingRoute: typeof PlayMatchingRoute
  PlayQuizRoute: typeof PlayQuizRoute
  StoriesStoryIdRoute: typeof StoriesStoryIdRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyId': {
      id: '/stories/$storyId'
      path: '/stories/$storyId'
      fullPath: '/stories/$storyId'
      preLoaderRoute: typeof StoriesStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/quiz': {
      id: '/play/quiz'
      path: '/play/quiz'
      fullPath: '/play/quiz'
      preLoaderRoute: typeof PlayQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/matching': {
      id: '/play/matching'
      path: '/play/matching'
      fullPath: '/play/matching'
      preLoaderRoute: typeof PlayMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/flashcards': {
      id: '/play/flashcards'
      path: '/play/flashcards'
      fullPath: '/play/flashcards'
      preLoaderRoute: typeof PlayFlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categoryId': {
      id: '/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/category/$categoryId'
      preLoaderRoute: typeof CategoryCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ages/$ageId': {
      id: '/ages/$ageId'
      path: '/ages/$ageId'
      fullPath: '/ages/$ageId'
      preLoaderRoute: typeof AgesAgeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgesAgeIdRoute: AgesAgeIdRoute,
  CategoryCategoryIdRoute: CategoryCategoryIdRoute,
  PlayFlashcardsRoute: PlayFlashcardsRoute,
  PlayMatchingRoute: PlayMatchingRoute,
  PlayQuizRoute: PlayQuizRoute,
  StoriesStoryIdRoute: StoriesStoryIdRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
